# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalInputLayout = QtWidgets.QHBoxLayout()
        self.horizontalInputLayout.setObjectName("horizontalInputLayout")
        self.input_title = QtWidgets.QLineEdit(self.centralwidget)
        self.input_title.setObjectName("input_title")
        self.horizontalInputLayout.addWidget(self.input_title)
        self.input_description = QtWidgets.QTextEdit(self.centralwidget)
        self.input_description.setObjectName("input_description")
        self.horizontalInputLayout.addWidget(self.input_description)
        self.input_due_date = QtWidgets.QDateEdit(self.centralwidget)
        self.input_due_date.setCalendarPopup(True)
        self.input_due_date.setObjectName("input_due_date")
        self.horizontalInputLayout.addWidget(self.input_due_date)
        self.input_priority = QtWidgets.QComboBox(self.centralwidget)
        self.input_priority.setObjectName("input_priority")
        self.input_priority.addItem("")
        self.input_priority.addItem("")
        self.input_priority.addItem("")
        self.horizontalInputLayout.addWidget(self.input_priority)
        self.input_category = QtWidgets.QComboBox(self.centralwidget)
        self.input_category.setObjectName("input_category")
        self.input_category.addItem("")
        self.input_category.addItem("")
        self.input_category.addItem("")
        self.horizontalInputLayout.addWidget(self.input_category)
        self.verticalLayout.addLayout(self.horizontalInputLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setObjectName("btn_add")
        self.buttonLayout.addWidget(self.btn_add)
        self.btn_update = QtWidgets.QPushButton(self.centralwidget)
        self.btn_update.setObjectName("btn_update")
        self.buttonLayout.addWidget(self.btn_update)
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setObjectName("btn_delete")
        self.buttonLayout.addWidget(self.btn_delete)
        self.btn_complete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_complete.setObjectName("btn_complete")
        self.buttonLayout.addWidget(self.btn_complete)
        self.btn_favorite = QtWidgets.QPushButton(self.centralwidget)
        self.btn_favorite.setObjectName("btn_favorite")
        self.buttonLayout.addWidget(self.btn_favorite)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.filterLayout = QtWidgets.QHBoxLayout()
        self.filterLayout.setObjectName("filterLayout")
        self.btn_filter = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter.setObjectName("btn_filter")
        self.filterLayout.addWidget(self.btn_filter)
        self.verticalLayout.addLayout(self.filterLayout)
        self.list_tasks = QtWidgets.QListWidget(self.centralwidget)
        self.list_tasks.setObjectName("list_tasks")
        self.verticalLayout.addWidget(self.list_tasks)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To-Do List"))
        self.input_title.setPlaceholderText(_translate("MainWindow", "Título de la tarea"))
        self.input_description.setPlaceholderText(_translate("MainWindow", "Descripción de la tarea"))
        self.input_priority.setToolTip(_translate("MainWindow", "Prioridad de la tarea"))
        self.input_priority.setItemText(0, _translate("MainWindow", "Baja"))
        self.input_priority.setItemText(1, _translate("MainWindow", "Media"))
        self.input_priority.setItemText(2, _translate("MainWindow", "Alta"))
        self.input_category.setToolTip(_translate("MainWindow", "Categoría de la tarea"))
        self.input_category.setItemText(0, _translate("MainWindow", "Trabajo"))
        self.input_category.setItemText(1, _translate("MainWindow", "Hogar"))
        self.input_category.setItemText(2, _translate("MainWindow", "Estudio"))
        self.btn_add.setText(_translate("MainWindow", "Agregar ➕"))
        self.btn_update.setText(_translate("MainWindow", "Actualizar 🔄"))
        self.btn_delete.setText(_translate("MainWindow", "Eliminar ❌"))
        self.btn_complete.setText(_translate("MainWindow", "Marcar Completada ✅"))
        self.btn_favorite.setText(_translate("MainWindow", "Marcar Favorita ⭐"))
        self.btn_filter.setText(_translate("MainWindow", "Filtrar por fecha 📆"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
