# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\todolist\src\todo_app\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalInputLayout = QtWidgets.QHBoxLayout()
        self.horizontalInputLayout.setObjectName("horizontalInputLayout")
        self.input_title = QtWidgets.QLineEdit(self.centralwidget)
        self.input_title.setObjectName("input_title")
        self.horizontalInputLayout.addWidget(self.input_title)
        self.input_description = QtWidgets.QTextEdit(self.centralwidget)
        self.input_description.setMaximumWidth(150)
        self.input_description.setMinimumWidth(100)
        self.input_description.setMinimumHeight(40)
        self.input_description.setMaximumHeight(60)
        self.input_description.setObjectName("input_description")
        self.horizontalInputLayout.addWidget(self.input_description)
        self.input_due_date = QtWidgets.QDateEdit(self.centralwidget)
        self.input_due_date.setCalendarPopup(True)
        self.input_due_date.setObjectName("input_due_date")
        self.horizontalInputLayout.addWidget(self.input_due_date)
        self.verticalLayout.addLayout(self.horizontalInputLayout)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.btn_add = QtWidgets.QPushButton(self.centralwidget)
        self.btn_add.setObjectName("btn_add")
        self.buttonLayout.addWidget(self.btn_add)
        self.btn_update = QtWidgets.QPushButton(self.centralwidget)
        self.btn_update.setObjectName("btn_update")
        self.buttonLayout.addWidget(self.btn_update)
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setObjectName("btn_delete")
        self.buttonLayout.addWidget(self.btn_delete)
        self.btn_filter = QtWidgets.QPushButton(self.centralwidget)
        self.btn_filter.setObjectName("btn_filter")
        self.buttonLayout.addWidget(self.btn_filter)
        self.verticalLayout.addLayout(self.buttonLayout)
        self.list_tasks = QtWidgets.QListWidget(self.centralwidget)
        self.list_tasks.setObjectName("list_tasks")
        self.verticalLayout.addWidget(self.list_tasks)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "To-Do List"))
        self.input_title.setPlaceholderText(_translate("MainWindow", "Título de la tarea"))
        self.input_description.setPlaceholderText(_translate("MainWindow", "Descripción de la tarea"))
        self.btn_add.setText(_translate("MainWindow", "Agregar ➕"))
        self.btn_update.setText(_translate("MainWindow", "Actualizar 🔄"))
        self.btn_delete.setText(_translate("MainWindow", "Eliminar ❌"))
        self.btn_filter.setText(_translate("MainWindow", "Filtrar por fecha 📆"))
